#!/bin/bash
# Jenkins Deploy Script
# Written by Simon Sinding - 2017 Github.com/TheSinding/


# The app name
APP_NAME="HoneyBase"

# Path to the app clone.
APP_DIR="$HOME/node_apps/$APP_NAME"

function error_exit
{
	echo "$1" 1>&2
	exit 1
}

hash pm2 2>/dev/null ||
{
#	error_exit "Error: PM2 is required but it's not installed.  Aborting.";
}
hash yarn 2>/dev/null ||
{
	error_exit "Error: Yarn is required but it's not installed.  Aborting.";
}
# Check if the app dir exist
if [ ! -d $APP_DIR ]; then
	error_exit "Error: $APP_DIR does not exist!"
fi
STOP_CURRENT_PROCESS(){
	pm2 stop $APP_NAME
}
# Build the node app
BUILD(){
	if yarn build; then
			echo "Successfully build"
	else
				error_exit "Build error! Aborting"
	fi	
}


# Run test's
TEST(){
	if yarn test; then 
		echo "Test passed"					
	else
					error_exit "Testing failed. Not deploying"
	fi
}

DEPLOY(){
	mv dist/ $APP_DIR
	pm2 start $APP_DIR/index.js --name $APP_NAME
	pm2 save
}
STOP_CURRENT_PROCESS
TEST
BUILD
DEPLOY
